# Indentation
set-option global tabstop 2
set-option global indentwidth 2

 # Highlighters
add-highlighter global/number-lines number-lines -hlcursor
add-highlighter global/show-matching show-matching
#add-highlighter global/show-whitespaces show-whitespaces

# Live reload
set-option global autoreload yes

# Copy to MacOS clipboard
hook global NormalKey y|d|c %{ nop %sh{
	printf %s "$kak_reg_dquote" | pbcopy
}}

# Editor Theme
colorscheme gruvbox

