filetype plugin indent on
syntax enable	" enable syntax highlighting
set clipboard=unnamed
set number	" Show line numbers
set nowrap	" Wrap lines
set nocompatible 
set showmatch	  " Highlight matching brace
set spell	  " Enable spell-checking
set cursorline
 
set hlsearch	" Highlight all search results
set smartcase	" Enable smart-case search
set ignorecase  " Always case-insensitive
set incsearch	" Searches for strings incrementally
 
set autoindent	  " Auto-indent new lines
set shiftwidth=2  " Number of auto-indent spaces
set smartindent	  " Enable smart-indent
set smarttab	  " Enable smart-tabs
set softtabstop=2 " Number of spaces per Tab
 
set ruler " Show row and column ruler information 
set undolevels=1000 " Number of undo levels
set backspace=indent,eol,start  " Backspace behaviour

set termguicolors

colorscheme miramare

" VIM backup files:
set backup
set backupdir=/tmp/
set dir=/tmp
